### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by azarboon**
I would suggest to add a template so beginners have an easier time onboarding ADR. Because it can be overwhelming for a beginner to consume listed materials. I've added a suggested template based on Mark Richard's video: https://www.youtube.com/watch?v=LMBqGPLvonU

### CODE REVIEW

**Comment by koppor** [comment]
we should not add another template 😅

why not simply using https://github.com/adr/madr/blob/develop/template%2Fadr-template-minimal.md

**Comment by azarboon** [comment]
> we should not add another template 😅
> 
> why not simply using https://github.com/adr/madr/blob/develop/template%2Fadr-template-minimal.md

Is this mentioned in the main page? If so, where exactly? I  searched for it but couldn't find it.

**Comment by azarboon** [comment]
I create a new PR to improve the existing template. I believe the template should be referenced in the main page and also MADR, be explained a bit more. I will make some changes soon.

**Comment by koppor** [comment]
> I create a new PR to improve the existing template. I believe the template should be referenced in the main page and also MADR, be explained a bit more. I will make some changes soon.

We did reference - but the length is a bit short:

image

Updates very welcome! A verbatim copy sounds great!

**Comment by koppor** [comment]
MADR currently offers four variants - I am not sure which variant to prominently present. I do not want to confuse readers.

Maybe, we should just present the full template: https://github.com/adr/madr/blob/develop/template/adr-template.md?plain=1. The bare https://github.com/adr/madr/blob/develop/template/adr-template-bare.md?plain=1 has all of it, but without guidance. Maybe, we need a mix of both? Not sure if we should extend `bare` (and keep the name) or add an additional variant 😅.

Refs https://github.com/adr/madr/pull/168

**Comment by azarboon** [comment]
> MADR currently offers four variants - I am not sure which variant to prominently present. I do not want to confuse readers.
> 
> Maybe, we should just present the full template: https://github.com/adr/madr/blob/develop/template/adr-template.md?plain=1. The bare https://github.com/adr/madr/blob/develop/template/adr-template-bare.md?plain=1 has all of it, but without guidance. Maybe, we need a mix of both? Not sure if we should extend `bare` (and keep the name) or add an additional variant 😅.
> 
> Refs [adr/madr#168](https://github.com/adr/madr/pull/168)

Thanks for explanation. Despite your instruction, it took me awhile to make sense of the page. I refined it a bit. I believe its now more coherent, and easier for a beginner to navigate and to make sense of.

**Comment by azarboon** [comment]
Also that mentioned Technology Radar volume is 6 years old. I dont think its relevant anymore so I removed it.

**Review by socadk — COMMENTED** [review]
The minimal MADR template is quite close to the Nygardian ADR template, no need to position it as an alternative.

**Comment by azarboon** [comment]
> The minimal MADR template is quite close to the Nygardian ADR template, no need to position it as an alternative.

Agreed. Removed it.

**Comment by azarboon** [comment]
I retitled the other section for better brevity. I'm open for better suggestions.

Also, I removed redundant links. This can make the overall page to be more reader-friendly.

**Comment by azarboon** [comment]
@koppor @socadk FYI: I've added the link to this project in Azure Documentation. So in their [official page for ADR](https://learn.microsoft.com/en-us/azure/well-architected/architect-role/architecture-decision-record), they are referring to only this project for further info.

**Comment by azarboon** [comment]
any update on this PR?  I believe now it's easier to understand. Can you please approve it?

**Comment by koppor** [comment]
> any update on this PR? I believe now it's easier to understand. Can you please approve it?

We changed the layout of the page (https://github.com/adr/adr.github.io/pull/58). - We are working on better sections. Thereby, we will try to use some of your updated texts. Let's see, how everything goes...

We also saw that you removed "MADR" from the list of "Collection of ADR Templates". - The whole section is a bit unstructured - with the update, it should get better...

**Comment by azarboon** [comment]
> > any update on this PR? I believe now it's easier to understand. Can you please approve it?
> 
> We changed the layout of the page (#58). - We are working on better sections. Thereby, we will try to use some of your updated texts. Let's see, how everything goes...
> 
> We also saw that you removed "MADR" from the list of "Collection of ADR Templates". - The whole section is a bit unstructured - with the update, it should get better...

OK. Please update me when you are done. Once we finalize this PR, we can work on other one.

**Comment by koppor** [comment]
> OK. Please update me when you are done. Once we finalize this PR, we can work on other one.

We are done now. Hope, you like the new appearance. Especially https://adr.github.io/adr-templates/.

(The chosen Template was the only one I found looking nice, lean, and maintainable - and I spend hours on this - I am aware that we don't get a TOC on the hompage on the right; but we accept it - https://github.com/cotes2020/jekyll-theme-chirpy/issues/2015).

---

All in all thank you for your text suggestions and we hope you like how they were incorporated in the new homepage.

**Pull request closed without merging**
