### PR TITLE
Migrate UML diagram to Mermaid

### PR DESCRIPTION
**Pull request by ParanoidUser**
Ahoy, @koppor! 👋 Hope you're not weary of these pull requests flood 🙃 In 2022, GitHub introduced [support for various diagrams](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams) in markdown files. The suggestion is to transition the current UML diagram (plantuml + png) to [Mermaid](https://mermaid.js.org/intro) diagram-as-code syntax rendered by GitHub. If you like this idea, we could also consider switching from UML to another diagram type, like a Flowchart. I'd love to hear your thoughts on this.

### Class Diagram
```mermaid
classDiagram
  direction TB
  class ADR {
    <<abstract>>
  }
  ADR <|-- MADR
  ADR <|-- YStatement
  ADR <|-- Nygard
```

### Flowchart

```mermaid
graph BT;
    MADR-->ADR;
    YStatement-->ADR;
    Nygard-->ADR;
```

### CODE REVIEW

**Comment by koppor** [comment]
I know both tools, but did not have time to switch. Thank you for doing it!

Each UML diagram has its intention. A flowchart is more a flow than showing the inheritance relations.

Which aspect do you miss and be displayed as diagram?

**Comment by koppor** [comment]
Is it possible to hide the class members in MermaidJS? Meaning `hide members` for MermaidJS?

**Comment by ParanoidUser** [comment]
> Is it possible to hide the class members in MermaidJS? Meaning `hide members` for MermaidJS?

Unfortunately, it's not currently possible to hide class members in MermaidJS. This [feature request](https://github.com/mermaid-js/mermaid/issues/3139) has been sitting in the backlog, and we're hoping it gets prioritized at some point. Personally, I find that having empty members/methods boxes doesn't look appealing, which is why I've started exploring other diagram types.

**Comment by koppor** [comment]
> > Is it possible to hide the class members in MermaidJS? Meaning `hide members` for MermaidJS?
> Unfortunately, it's not currently possible to hide class members in MermaidJS. This [feature request](https://github.com/mermaid-js/mermaid/issues/3139) has been sitting in the backlog, and we're hoping it gets prioritized at some point. Personally, I find that having empty members/methods boxes doesn't look appealing, which is why I've started exploring other diagram types.

For me, the important thing of the diagram is the semantics of inheritance. Thus, there is IMHO no other diagram type. Especially, the arrows should be the inheritance arrows specified by UML.

Empty boxes are perfectly legal in UML class diagrams. See https://stackoverflow.com/a/30381979/873282.

I like them more, because of less visual clutter.

In PlantUML, it is possible to use graphviz directly. Then, one can do tweaks if one wants. I think, this is not possible with MermaidJS.

Maye, we have to wait until https://github.com/mermaid-js/mermaid/issues/3139 is resolved.

**Comment by ParanoidUser** [comment]
Nice move! I'll touch base with the Mermaid team to find out their progress on the feature.

**Comment by koppor** [comment]
> Nice move! I'll touch base with the Mermaid team to find out their progress on the feature.

Or try to contribute directly :p

**Comment by koppor** [comment]
I am trying to switch to the [Chirpy Jekyll Theme](https://github.com/cotes2020/jekyll-theme-chirpy). There, mermaid is said to work. Thus, I am merging it to my brancha of my tests.

**Pull request merged**
